config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :destroy]

  resources :circles do
    resources :memberships, only: [:index, :create], module: :circles do
      resource :acceptance, only: [:create], module: :memberships
    end
    resources :comments, only: [:edit, :new, :create, :update], module: :circles
  end

  resources :comments, only: [:destroy]
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :name,
  	presence: true,
  	uniqueness: true

  validates :description,
  	presence: true,
  	length: { minimum: 10 }

  validates :members_count, 
  	presence: true

  has_many :memberships

  has_many :members,
    class_name: 'User',
    source: :user,
    through: :memberships

  has_many :comments
end

app/controllers/circles/comments_controller.rb
class Circles::CommentsController < ApplicationController
  before_action :set_circle
  before_action :set_comment, only: [:edit, :update]

  def new
  	# circle_idを引き継ぎさせる
  	# set_circle

  	# @circleとcommentsを組み立てる(build)
  	@comment = @circle.comments.build
    authorize @comment
  end

  def create
  	# set_circle

  	# buildとnewは同じ働きをする
  	@comment = @circle.comments.build(comment_params)
  	if @comment.save
  		redirect_to circle_path(@circle), notice: 'コメント作成しました'
  	else
  		flash.now.alert = 'コメント作成に失敗しました'
  		render :new
  	end
  end

  def edit
    # 親をfind
  	# set_circle

    # 子をfind
    # set_comment
  end

  def update
  	# set_circle
    # set_comment

  	if @comment.update(comment_params)
      # circleのshowに飛ばす
  		redirect_to @circle
  	else
  		render 'edit'
  	end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:content).merge(user_id: session[:user_id])
  	end

    def set_circle
      @circle = Circle.find(params[:circle_id])
    end

    def set_comment
      @comment = @circle.comments.find(params[:id])
    end
end

app/controllers/circles/memberships/acceptances_controller.rb
class Circles::Memberships::AcceptancesController < ApplicationController
  def create
  	@circle = Circle.find(params[:circle_id])
  	@membership = @circle.memberships.find(params[:membership_id])
  	@membership.member!
  	redirect_to circle_memberships_path(@circle), notice: '承認しました'
  end
end

app/controllers/circles/memberships_controller.rb
class Circles::MembershipsController < ApplicationController
  before_action :set_circle

  def index
    @memberships = @circle.memberships
  end


  def create
  	# session[:user_id]を取得
  	@membership = @circle.memberships.build(role: :pending, user_id: session[:user_id])
  	if @membership.save
      MembershipMailer.new_member(@circle).deliver_now
  		redirect_to circles_path(@circle), notice: '管理者に申請を送りました'
  	else
  		flash.now.alert = '申請を送れませんでした'
  		render :new
  	end
  end

  private
    def set_circle
      @circle = Circle.find(params[:circle_id])
    end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :authenticate_user
  before_action :set_circle, only: [:show, :edit, :update, :destroy]

  def index
    # policiesで対応ファイル指定
    authorize Circle
    @circles = Circle.all.order(updated_at: :desc)
  end

  def show
    # circleのidを受け取る

    # policiesで対応ファイル指定
    # authorize @circle

    # include?メソッドは、配列の要素に引数objが含まれていればtrue
    if !@circle.members.include?(current_user)
      redirect_to :back, alert: 'まだ参加してない' and return
    end

    # 最新時間の順のに並べ、変数に入れる
    @comments = @circle.comments.order(created_at: :desc)
  end

  def new
    @circle = Circle.new
    authorize @circle
  end

  def create
    @circle = Circle.new(circle_params)
    authorize @circle

    # errorがおきそうな所を begin rescueで囲む
    begin
      ActiveRecord::Base.transaction do
        # dbに２回保存させるから、わざと例外を起こさせる !
        @circle.save!
        @circle.memberships.create!(user: current_user, role: :owner)
      end
      redirect_to circles_path, notice: 'サークル作成しました'
    rescue => e
      logger.error e.inspect + e.backtrace.join("\n")
      flash.now.alert = '作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @circle.update(circle_params)
      redirect_to @circle, notice: "変更しました"
    else
      flash.now.alert = "変更できませんでした"
      render :edit
    end
  end

  def destroy
    @circle.destroy
    redirect_to circles_path, notice: 'サークルを削除しました'
  end

  private
    def circle_params
      params.require(:circle).permit(:name, :description)
    end

    def set_circle
      @circle = Circle.find(params[:id])
      authorize @circle
    end
end

app/helpers/circles/comments_helper.rb
module Circles::CommentsHelper
end

app/helpers/circles/memberships_helper.rb
module Circles::MembershipsHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<%= form_for @circle do |f| %>
<%#  %>
<%= @circle.errors.full_messages.to_json %>
	<div class="name">
		<%= f.label :name, 'Circle name' %>
		<%= f.text_field :name, placeholder: 'name' %>
	</div>
	<div class="description">
		<%= f.label :description, 'Circle description' %>
		<%= f.text_area :description, size: '50*200', placeholder: 'description' %>
	</div>
	<br>
	<%= f.submit 'create' %>
<% end %>

app/views/circles/create.html.erb
<h1>Circles#create</h1>

app/views/circles/destroy.html.erb
<h1>Circles#destroy</h1>
<p>Find me in app/views/circles/destroy.html.erb</p>

app/views/circles/edit.html.erb
<h1>Circles#edit</h1>

<%= render 'form' %>
<%= link_to 'Back', circles_path %>

app/views/circles/index.html.erb
<style type="text/css">
.table2 th {
  background-color: #cccccc;
}
</style>

<% user = User.find(session[:user_id]) %>
<p><strong>-----------------------------------お帰りなさい：<%= user.name %></strong> さん</p>

<h1>Circles#index</h1>
<table class="table2" border=1>
	<tr>
		<th>
			<p>Circle name</p>
		</th>
		<th>
			<p>Circle member</p>
		</th>
		<th>
			<p>Circle description</p>
		</th>
		<th>
			<p>Circle create time</p>
		</th>
		<th>
			<p>Circle update time</p>
		</th>
		<th>
			<p>member</p>
		</th>
		<th>
			<p>edit</p>
		</th>
		<th>
			<p>destroy</p>
		</th>
		<th>
			<p>join</p>
		</th>
	</tr>
	<% @circles.each do |circle| %>
		<tr>
			<td><%= link_to circle.name, circle_path(circle) %></td>

			<td>
			<%# memberになったら人数を増やす %>
			<%# if circle.id == 'member' && circle.id == 'owner' %>
				<center><%= circle.members_count %> 名</center>
			<%# end %>
			</td>

			<%# 文字数制限 20文字 %>
			<td><%= circle.description.truncate(20) %></td>
			<td><%= circle.created_at %></td>
			<td><%= circle.updated_at %></td>
			<td><center><h3><%= link_to 'list', circle_memberships_path(circle) %></h3></center></td>

			<%# ボタンの出し分け %>
			<% if policy(circle).update? %>
				<td><h3><%= link_to 'edit', edit_circle_path(circle) %></h3></td>
				<td>
					<h3>
						<%# if %>
							<%= link_to 'destroy', circle_path(circle), data: { method: :delete, confirm: 'Are you sure? '} %>
						<%# end %>
					</h3>
				</td>
			<% else %>
				<td></td>
				<td></td>
			<% end %>
			<td>
				<%# policyを build %>
				<% if policy(circle.memberships.build).create? %>
					<%# include?メソッドは、配列の要素に引数objが含まれていればtrue %>
					<h3><%= link_to 'join', circle_memberships_path(circle), data: { method: 'post' } %></h3>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>
<br>
<h3><%= link_to 'create circle', controller: 'circles', action: 'new' %></h3>

app/views/circles/new.html.erb
<h1>Circles#new</h1>

<%= render 'form' %>
<br>
<%= link_to 'back', :back %>

app/views/circles/show.html.erb
<h1>Circles#show</h1>

<h2>Circle Name</h2>
<p><%= @circle.name %></p>
<h2>Circle Description</h2>
<p><%= @circle.description %></p>
<h2>Circle Member <%= @circle.members_count %> 人</h2>
<% @circle.members.each do |member| %>
	<p><%= member.name %> さん</p>
<% end %>
<h2>Comment list <%= @circle.comments.count %>件</h2>

<%# commentの配列をcountする %>
<% if @comments.count == 0 %>
	<p>コメントはありません</p>
<% else %>

	<%# @commentsの配列をcommnetのキーに入れる %>
	<% @comments.each do |comment| %>
		<p>---------------------------------</p>
		<p>
			<%# commentキーを使い、欲しいカラムを取得 %>
			<%= comment.content %>
		</p>
		<%= comment.created_at %>
		<% if policy(@circle).update? %>
			<h3>
				<%= link_to 'destroy', comment_path(comment),method: :delete %> |
				<%= link_to 'edit', edit_circle_comment_path(@circle, comment) %>
			</h3>
		<% end %>
	<% end %>
<% end %>
<p>---------------------------------</p>

<%# circleを継承させる %>
<h3><%= link_to 'create comment', new_circle_comment_path(@circle) %></h3>

<%# 権限処理 %>
<% if policy(@circle).edit? %>
	<h2>Circle</h2>
	<h3>
		<%= link_to 'edit', edit_circle_path(@circle) %>
	</h3>
<% end %>
<h3><%= link_to 'back', circles_path %></h3>

app/views/circles/update.html.erb
<h1>Circles#update</h1>
<p>Find me in app/views/circles/update.html.erb</p>